import { Airport } from "src/models";
export const dummyAirports: Airport[] = [
  {
    name: "Hasanuddin International Airport",
    city: "Ujung Pandang",
    code: "UPG",
    country: "Indonesia",
  },
  {
    name: "Ngurah Rai (Bali) International Airport",
    city: "Denpasar",
    code: "DPS",
    country: "Indonesia",
  },
  {
    name: "Dortheys Hiyo Eluay International Airport",
    city: "Sentani",
    code: "DJJ",
    country: "Indonesia",
  },
  {
    name: "Sultan Aji Muhammad Sulaiman Sepinggan International Airport",
    city: "Balikpapan",
    code: "BPN",
    country: "Indonesia",
  },
  {
    name: "Juanda International Airport",
    city: "Surabaya",
    code: "SUB",
    country: "Indonesia",
  },
  {
    name: "Soekarno-Hatta International Airport",
    city: "Jakarta",
    code: "CGK",
    country: "Indonesia",
  },
  {
    name: "Kualanamu International Airport",
    city: "Bandara Kuala Namu",
    code: "KNO",
    country: "Indonesia",
  },
  {
    name: "Sangia Nibandera Airport",
    city: "Kolaka",
    code: "KXB",
    country: "Indonesia",
  },
  {
    name: "Bilogai-Sugapa Airport",
    city: "Sugapa",
    code: "UGU",
    country: "Indonesia",
  },
  {
    name: "Frans Kaisiepo Airport",
    city: "Biak",
    code: "BIK",
    country: "Indonesia",
  },
  {
    name: "Nabire Airport",
    city: "Nabire",
    code: "NBX",
    country: "Indonesia",
  },
  {
    name: "Mozes Kilangin Airport",
    city: "Timika",
    code: "TIM",
    country: "Indonesia",
  },
  {
    name: "Lombok International Airport",
    city: "Mataram",
    code: "LOP",
    country: "Indonesia",
  },
  {
    name: "Pitu Airport",
    city: "Gotalalamo-Morotai Island",
    code: "OTI",
    country: "Indonesia",
  },
  {
    name: "Toraja Airport",
    city: "Toraja",
    code: "TRT",
    country: "Indonesia",
  },
  {
    name: "Mutiara - SIS Al-Jufrie Airport",
    city: "Palu",
    code: "PLW",
    country: "Indonesia",
  },
  {
    name: "Kasiguncu Airport",
    city: "Poso-Celebes Island",
    code: "PSJ",
    country: "Indonesia",
  },
  {
    name: "Syukuran Aminuddin Amir Airport",
    city: "Luwok",
    code: "LUW",
    country: "Indonesia",
  },
  {
    name: "Tjilik Riwut Airport",
    city: "Palangkaraya",
    code: "PKY",
    country: "Indonesia",
  },
  {
    name: "Yogyakarta International Airport",
    city: "Yogyakarta",
    code: "YIA",
    country: "Indonesia",
  },
  {
    name: "Tunggul Wulung Airport",
    city: "Cilacap",
    code: "CXP",
    country: "Indonesia",
  },
  {
    name: "Oksibil Airport",
    city: "Oksibil",
    code: "OKL",
    country: "Indonesia",
  },
  {
    name: "Mopah International Airport",
    city: "Merauke",
    code: "MKQ",
    country: "Indonesia",
  },
  {
    name: "Tanah Merah Airport",
    city: "Tanah Merah",
    code: "TMH",
    country: "Indonesia",
  },
  {
    name: "Kalimarau Airport",
    city: "Tanjung Redeb - Borneo Island",
    code: "BEJ",
    country: "Indonesia",
  },
  {
    name: "Juwata International Airport / Suharnoko Harbani AFB",
    city: "Tarakan",
    code: "TRK",
    country: "Indonesia",
  },
  {
    name: "Aji Pangeran Tumenggung Pranoto International Airport",
    city: "Samarinda",
    code: "AAP",
    country: "Indonesia",
  },
  {
    name: "Naha Airport",
    city: "Tahuna-Sangihe Island",
    code: "NAH",
    country: "Indonesia",
  },
  {
    name: "Sam Ratulangi Airport",
    city: "Manado",
    code: "MDC",
    country: "Indonesia",
  },
  {
    name: "Sultan Babullah Airport",
    city: "Sango",
    code: "TTE",
    country: "Indonesia",
  },
  {
    name: "Warukin Airport",
    city: "Tanta-Tabalong",
    code: "TJG",
    country: "Indonesia",
  },
  {
    name: "Syamsudin Noor International Airport",
    city: "Landasan Ulin",
    code: "BDJ",
    country: "Indonesia",
  },
  {
    name: "Karel Sadsuitubun Airport",
    city: "Langgur",
    code: "LUV",
    country: "Indonesia",
  },
  {
    name: "Pattimura International Airport",
    city: "Ambon",
    code: "AMQ",
    country: "Indonesia",
  },
  {
    name: "Abdul Rachman Saleh Airport",
    city: "Malang",
    code: "MLG",
    country: "Indonesia",
  },
  {
    name: "Adisutjipto International Airport",
    city: "Yogyakarta",
    code: "JOG",
    country: "Indonesia",
  },
  {
    name: "Adisumarmo International Airport",
    city: "Surakarta",
    code: "SOC",
    country: "Indonesia",
  },
  {
    name: "Achmad Yani Airport",
    city: "Semarang",
    code: "SRG",
    country: "Indonesia",
  },
  {
    name: "Fakfak Airport",
    city: "Fakfak",
    code: "FKQ",
    country: "Indonesia",
  },
  {
    name: "Kaimana Airport",
    city: "Kaimana",
    code: "KNG",
    country: "Indonesia",
  },
  {
    name: "Babo Airport",
    city: "Babo",
    code: "BXB",
    country: "Indonesia",
  },
  {
    name: "Rendani Airport",
    city: "Manokwari",
    code: "MKW",
    country: "Indonesia",
  },
  {
    name: "Wamena Airport",
    city: "Wamena",
    code: "WMX",
    country: "Indonesia",
  },
  {
    name: "Matahora Airport",
    city: "Wangi-wangi Island",
    code: "WNI",
    country: "Indonesia",
  },
  {
    name: "Domine Eduard Osok Airport",
    city: "Sorong",
    code: "SOQ",
    country: "Indonesia",
  },
  {
    name: "Sultan Syarif Kasim II International Airport / Roesmin Nurjadin AFB",
    city: "Pekanbaru",
    code: "PKU",
    country: "Indonesia",
  },
  {
    name: "Pinang Kampai Airport",
    city: "Dumai",
    code: "DUM",
    country: "Indonesia",
  },
  {
    name: "Japura Airport",
    city: "Rengat-Sumatra Island",
    code: "RGT",
    country: "Indonesia",
  },
  {
    name: "Kertajati International Airport",
    city: "Kertajati",
    code: "KJT",
    country: "Indonesia",
  },
  {
    name: "Husein Sastranegara International Airport",
    city: "Bandung",
    code: "BDO",
    country: "Indonesia",
  },
  {
    name: "Hang Nadim International Airport",
    city: "Batam",
    code: "BTH",
    country: "Indonesia",
  },
  {
    name: "Halim Perdanakusuma International Airport",
    city: "Jakarta",
    code: "HLP",
    country: "Indonesia",
  },
  {
    name: "Radin Inten II International Airport",
    city: "Bandar Lampung",
    code: "TKG",
    country: "Indonesia",
  },
  {
    name: "Binaka Airport",
    city: "Gunungsitoli",
    code: "GNS",
    country: "Indonesia",
  },
  {
    name: "Aek Godang Airport",
    city: "Padang Sidempuan",
    code: "AEG",
    country: "Indonesia",
  },
  {
    name: "Tabing Airport",
    city: "Padang",
    code: "",
    country: "Indonesia",
  },
  {
    name: "Soewondo Air Force Base",
    city: "Medan",
    code: "MES",
    country: "Indonesia",
  },
  {
    name: "Dr. Ferdinand Lumban Tobing Airport",
    city: "Sibolga (Pinangsori)",
    code: "FLZ",
    country: "Indonesia",
  },
  {
    name: "Nanga Pinoh Airport",
    city: "Nanga Pinoh-Borneo Island",
    code: "NPO",
    country: "Indonesia",
  },
  {
    name: "Rahadi Osman Airport",
    city: "Ketapang",
    code: "KTG",
    country: "Indonesia",
  },
  {
    name: "Ranai-Natuna Airport",
    city: "Ranai-Natuna Besar Island",
    code: "NTX",
    country: "Indonesia",
  },
  {
    name: "Supadio Airport",
    city: "Pontianak",
    code: "PNK",
    country: "Indonesia",
  },
  {
    name: "Pangsuma Airport",
    city: "Putussibau-Borneo Island",
    code: "PSU",
    country: "Indonesia",
  },
  {
    name: "Sintang Airport",
    city: "Sintang",
    code: "SQG",
    country: "Indonesia",
  },
  {
    name: "Fatmawati Soekarno Airport",
    city: "Bengkulu",
    code: "BKS",
    country: "Indonesia",
  },
  {
    name: "Sultan Mahmud Badaruddin II Airport",
    city: "Palembang",
    code: "PLM",
    country: "Indonesia",
  },
  {
    name: "Pendopo Airport",
    city: "Talang Gudang-Sumatra Island",
    code: "PDO",
    country: "Indonesia",
  },
  {
    name: "Minangkabau International Airport",
    city: "Padang (Katapiang)",
    code: "PDG",
    country: "Indonesia",
  },
  {
    name: "Cut Nyak Dhien Airport",
    city: "Kuala Pesisir",
    code: "MEQ",
    country: "Indonesia",
  },
  {
    name: "Rembele Airport",
    city: "Takengon",
    code: "TXE",
    country: "Indonesia",
  },
  {
    name: "Lhok Sukon Airport",
    city: "Lhok Sukon-Sumatra Island",
    code: "LSX",
    country: "Indonesia",
  },
  {
    name: "Sultan Iskandar Muda International Airport",
    city: "Banda Aceh",
    code: "BTJ",
    country: "Indonesia",
  },
  {
    name: "Stevanus Rumbewas Airport",
    city: "Serui",
    code: "ZRI",
    country: "Indonesia",
  },
];
